{{- $loadbalancerIP  := .Values.service.loadBalancerIP -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gofipe.fullname" . }}
  labels:
    {{- include "gofipe.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $loadbalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gofipe.selectorLabels" . | nindent 4 }}
